server:
  port: 8080
  address: ${HOST_ADDR:localhost}

mob-builder:
  port: 8081

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:root@localhost:27017/}
      database: ${DB_NAME:MobBuilder}