server:
  port: 8080
  address: ${HOST_ADDR:localhost}

mob-builder:
  port: 8081

spring:
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      password: ${DB_PWD}
      username: ${DB_USER:neo4j}